name: Build pull request
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build-pull-request:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: actions/setup-node@v1 #this installs node and npm for us
        with:
          node-version: "10.x"
      # Build the Angular application to the dist folder
      - name: Build Angular application
        run: |
          cd kerberos.ng
          npm install
          npm run build
      # Build the Docker image with the latest tag and the release tag
      - name: Build Docker image
        run: |
          docker build -t uugai/kerberos-documentation:latest .
